pipeline:
  build_and_deploy_code:
    image: maven
    privileged: false
    when:
      branch: [master, develop]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [ access_key, access_key_id ]
    commands:
      - ./build-deploy.sh

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push
        - pull_request

#  deploy_docker_image:
#    image: docker:17.09.0-ce
#    secrets:
#      - docker_password
#    privileged: false
#    when:
#      branch: [master, develop]
#    environment:
#      - DOCKER_HOST=tcp://172.17.0.1:2375
#    commands:
#      - apk update
#      - apk add libxml2-utils
#      - ./docker-deploy.sh egar-workflow-api
