pipeline:
  build_and_deploy_code:
    image: maven
    privileged: false
    when:
      branch: [master, develop]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [ access_key, access_key_id ]
    commands:
      - ./build-deploy.sh
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    when:
      status: [success, failure]
  deploy_docker_image:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    privileged: false
    when:
      branch: [master, develop]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - apk update
      - apk add libxml2-utils
      - ./docker-deploy.sh egar-workflow-api
  deploy_to_acp:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    secrets:
      - kube_server
      - kube_token
    commands:
      - ./acp-deploy.sh
    when:
      event: deployment
